<a href="https://colab.research.google.com/github/Phenaoj/Entregables-BIT-PaulaHenao/blob/main/Entregable_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
#CARGA DEL LA BASE DE DATOS Y LIBRERÍAS
import pandas as pd
import numpy as np
from google.colab import files
uploaded =files.upload()

Saving animal_data_dirty1.csv to animal_data_dirty1 (1).csv

In [19]:
# 1. DIAGNÓSTICO INICIAL
df = pd.read_csv("animal_data_dirty1 (1).csv", sep=";")

# ¿Cuántas filas y columnas tiene el Data Frame?
df.shape

(1011, 11)

In [12]:
#¿Cuáles son las columnas y que tipo de datos tiene cada una?
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       991 non-null    object
 1   Country           999 non-null    object
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    object
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     object
 9   Observation date  1011 non-null   object
 10  Data compiled by  1011 non-null   object
dtypes: float64(5), object(6)
memory usage: 87.0+ KB

In [15]:
#¿Cuántos valores faltantes existen por columna?
df.isnull().sum()

Animal type           20
Country               12
Weight kg             27
Body Length cm        27
Gender                19
Animal code         1011
Latitude              98
Longitude             98
Animal name          959
Observation date       0
Data compiled by       0
dtype: int64

In [18]:
#¿Cuántos registros duplicados existen?
df.duplicated().sum()

np.int64(167)

In [23]:
#Detección de valores sospechosos e incosistentes
for columna in df.select_dtypes(include="object").columns:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts(dropna=False))

#Problemas identificados: las columnas como Animal type, Country, Gender, Animal Name contienen valores vacios los cuales se deben analizar si son datos relevantes para tener en cuenta o solo harían ruido en el análisis,
#en la columna Animal type se encuentra una misma especie escrita de dos maneras diferentes,
#en la columna Country contamos con los nombres completos pero también con las abreviaciones.

--- Animal type ---
Animal type
red squirrel       543
hedgehog           274
lynx                61
European bison      49
red squirrell       22
NaN                 20
red squirel         14
lynx?               10
European bison™      6
European buster      4
European bisson      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

--- Country ---
Country
Poland            291
Germany           176
Slovakia          151
Hungary           146
Czech Republic    103
Austria            74
PL                 15
NaN                12
HU                 11
Hungry             10
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

--- Gender ---
Gender
male              499
female            488
NaN                19
not determined      5
Name: count, dtype: int64

--- Animal name ---
Animal name
NaN           959
Bob Bobson     18
Basia          10
Lola            9
Lolek           4
Zuzia           4
Puchatek        2
Sissi           2
Szefu           1
Klucha          1
Bibi            1
Name: count, dtype: int64

--- Observation date ---
Observation date
01.03.2024    61
02.03.2024    47
06.04.2024    45
04.03.2024    43
02.04.2024    41
              ..
07.06.2024     1
03.14.2024     1
03.13.2024     1
03.11.2024     1
8 May 2024     1
Name: count, Length: 114, dtype: int64

--- Data compiled by ---
Data compiled by
Anne Anthony     473
Bob Bobson       259
John Johnson     249
James Johnson     30
Name: count, dtype: int64

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony
5,European bisson,Poland,900.0,295.0,male,NaN,52.834759,23.817201,NaN,01.03.2024,Anne Anthony

In [25]:
# 2. LIMPIEZA DE DATOS
df.head(6)

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony
5,European bisson,Poland,900.0,295.0,male,NaN,52.834759,23.817201,NaN,01.03.2024,Anne Anthony

In [26]:
# Identificar las columnas con valores faltantes y aplica una estrategia de tratamiento adecuada.
df[df["Animal type"].isna()]

# Se puede identificar que una gran mayoría de los registros que tienen valores faltantes en el Animal Type, no aportan información relevante ya que casi todas las columnas están vacías; por consiguiente se puede descartar dichos valores.

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.03.2024,James Johnson
164,NaN,Austria,0.263,22.0,male,NaN,NaN,NaN,NaN,05.03.2024,Bob Bobson
563,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.04.2024,James Johnson
626,NaN,Austria,0.319,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
627,NaN,Austria,0.292,19.0,female,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
628,NaN,Austria,0.319,19.0,female,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
629,NaN,Austria,0.298,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
630,NaN,Austria,0.255,22.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
631,NaN,Austria,0.300,20.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
632,NaN,Austria,0.252,21.0,male,NaN,NaN,NaN,NaN,06.04.2024,Bob Bobson
833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.05.2024,James Johnson
934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.06.2024,James Johnson
956,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.07.2024,James Johnson
963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.08.2024,James Johnson
968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.13.2024,James Johnson
969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.14.2024,James Johnson
970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson
971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.22.2024,James Johnson

In [29]:
df = df.dropna(subset=["Animal type"])

# Detectar y elimina los registros duplicados cuando corresponda.
# Se va a eliminar aquellas filas que sean completamente iguales
df = df.drop_duplicates()

In [31]:
#Corrección de la columna Animal Type
#Para el caso de Ledgehod, Wedgehod y Hedgehog, se busca en internet y solo el úlitmo nombre arroja un resultado de especie de animales, por ende se estandarizará a dicha especie.
#Caso análogo con el European bison.
df["Animal type"] = df["Animal type"].replace({
    "red squirrell": "red squirrel",
    "red squirel": "red squirrel",
    "ledgehod": "hedgehog",
    "wedgehod": "hedgehog",
    "European bisson": "European bison",
    "European buster": "European bison",
    "European bison™": "European bison",
    "lynx?": "lynx"})

#Corrección de la columna Country
# Estándarizar las abreviaciones del país a su nombre
df["Country"] = df["Country"].replace({
    "PL": "Poland",
    "DE": "Germany",
    "HU": "Hungary",
    "Hungry": "Hungary",
    "CZ": "Czech Republic",
    "Czech": "Czech Republic"})

In [39]:
#Estandarización del formato para la columan Observation Date, se verifica si después de los cambios aplicados aún existen fechas en otro formato
print(df["Observation date"].dtype)
df["Observation date"].isna().sum()

#Como ya se encuentra en el formato adecuado y no hay valores vacíos, no es necesario hacer nada más.

datetime64[ns]

np.int64(0)

In [40]:
#Comprobación de la limpieza
df.shape

#Pasamos de 1011 filas a 825

(825, 11)

In [44]:
df.duplicated().sum()

#Ya no tenemos valores duplicados

np.int64(0)

In [43]:
for columna in ["Animal type", "Country"]:
    print(f"\n--- {columna} ---")
    print(df[columna].value_counts(dropna=False))

#Ya en Animal Type no existe registros vacios, además se simplificaron la cantidad de animales, para Country ya no se encuentra las abreviaciones, solo los nombres completos de los paises.

--- Animal type ---
Animal type
red squirrel      413
hedgehog          278
lynx               71
European bison     63
Name: count, dtype: int64

--- Country ---
Country
Poland            192
Germany           178
Slovakia          151
Hungary           118
Czech Republic    112
Austria            66
Australia           4
CC                  4
Name: count, dtype: int64